export const playerData = [
    {
      id: 1,
      playerimage: "https://i.postimg.cc/SRnHNDb2/Rayan-Ros.jpg",
      playername: "John Doe",
      playergender: "Male",
      playertype: "Batsman",
      playerbirthdate: "1990-05-15",
      playeraddress: "New York, USA",
      totalmatches: "120",
      totalscore: "5800",
      totalfifties: "35",
      totalcenturies: "12",
      highestscore: "200",
      totalwickets: "15",
      highestwickets: "5",
      playeraverage: "48.3",
      playerstrikerate: "85.6",
      playerdetail: "Experienced right-handed batsman with solid technique."
    },
    {
      id: 2,
      playerimage: "https://i.postimg.cc/HxKJbZw5/Atish-Sahu.jpg",
      playername: "Jane Smith",
      playergender: "Female",
      playertype: "Bowler",
      playerbirthdate: "1992-09-30",
      playeraddress: "London, UK",
      totalmatches: "95",
      totalscore: "2200",
      totalfifties: "5",
      totalcenturies: "1",
      highestscore: "105",
      totalwickets: "150",
      highestwickets: "7",
      playeraverage: "23.4",
      playerstrikerate: "72.5",
      playerdetail: "A left-arm fast bowler with consistent performance in all formats."
    },
    {
      id: 3,
      playerimage: "https://i.postimg.cc/g0gL2krg/Lipun-Sahu.jpg",
      playername: "Ravi Kumar",
      playergender: "Male",
      playertype: "AllRounder",
      playerbirthdate: "1988-11-21",
      playeraddress: "Delhi, India",
      totalmatches: "150",
      totalscore: "4000",
      totalfifties: "28",
      totalcenturies: "5",
      highestscore: "175",
      totalwickets: "250",
      highestwickets: "6",
      playeraverage: "35.6",
      playerstrikerate: "90.2",
      playerdetail: "Versatile all-rounder excelling in both batting and bowling."
    },
    {
      id: 4,
      playerimage: "https://i.postimg.cc/s1CvNM0g/Karan-Singh.jpg",
      playername: "Emily Davis",
      playergender: "Female",
      playertype: "Batsman",
      playerbirthdate: "1995-03-12",
      playeraddress: "Sydney, Australia",
      totalmatches: "80",
      totalscore: "3700",
      totalfifties: "20",
      totalcenturies: "6",
      highestscore: "180",
      totalwickets: "10",
      highestwickets: "3",
      playeraverage: "44.5",
      playerstrikerate: "82.7",
      playerdetail: "Aggressive opening batter known for quick scoring."
    },
    {
      id: 5,
      playerimage: "https://i.postimg.cc/JhrB8B7y/Nick-Dera.jpg",
      playername: "Carlos Mendes",
      playergender: "Male",
      playertype: "Bowler",
      playerbirthdate: "1987-08-10",
      playeraddress: "Rio de Janeiro, Brazil",
      totalmatches: "110",
      totalscore: "1500",
      totalfifties: "3",
      totalcenturies: "0",
      highestscore: "72",
      totalwickets: "200",
      highestwickets: "8",
      playeraverage: "27.3",
      playerstrikerate: "78.9",
      playerdetail: "A right-arm medium pacer with great control over line and length."
    },
    {
      id: 6,
      playerimage: "https://i.postimg.cc/SRnHNDb2/Rayan-Ros.jpg",
      playername: "John Doe",
      playergender: "Male",
      playertype: "Batsman",
      playerbirthdate: "1990-05-15",
      playeraddress: "New York, USA",
      totalmatches: "120",
      totalscore: "5800",
      totalfifties: "35",
      totalcenturies: "12",
      highestscore: "200",
      totalwickets: "15",
      highestwickets: "5",
      playeraverage: "48.3",
      playerstrikerate: "85.6",
      playerdetail: "Experienced right-handed batsman with solid technique."
    },
    {
      id: 7,
      playerimage: "https://i.postimg.cc/HxKJbZw5/Atish-Sahu.jpg",
      playername: "Jane Smith",
      playergender: "Female",
      playertype: "Bowler",
      playerbirthdate: "1992-09-30",
      playeraddress: "London, UK",
      totalmatches: "95",
      totalscore: "2200",
      totalfifties: "5",
      totalcenturies: "1",
      highestscore: "105",
      totalwickets: "150",
      highestwickets: "7",
      playeraverage: "23.4",
      playerstrikerate: "72.5",
      playerdetail: "A left-arm fast bowler with consistent performance in all formats."
    },
    {
      id: 8,
      playerimage: "https://i.postimg.cc/g0gL2krg/Lipun-Sahu.jpg",
      playername: "Ravi Kumar",
      playergender: "Male",
      playertype: "AllRounder",
      playerbirthdate: "1988-11-21",
      playeraddress: "Delhi, India",
      totalmatches: "150",
      totalscore: "4000",
      totalfifties: "28",
      totalcenturies: "5",
      highestscore: "175",
      totalwickets: "250",
      highestwickets: "6",
      playeraverage: "35.6",
      playerstrikerate: "90.2",
      playerdetail: "Versatile all-rounder excelling in both batting and bowling."
    },
    {
      id: 9,
      playerimage: "https://i.postimg.cc/s1CvNM0g/Karan-Singh.jpg",
      playername: "Emily Davis",
      playergender: "Female",
      playertype: "Batsman",
      playerbirthdate: "1995-03-12",
      playeraddress: "Sydney, Australia",
      totalmatches: "80",
      totalscore: "3700",
      totalfifties: "20",
      totalcenturies: "6",
      highestscore: "180",
      totalwickets: "10",
      highestwickets: "3",
      playeraverage: "44.5",
      playerstrikerate: "82.7",
      playerdetail: "Aggressive opening batter known for quick scoring."
    },
    {
      id: 10,
      playerimage: "https://i.postimg.cc/JhrB8B7y/Nick-Dera.jpg",
      playername: "Carlos Mendes",
      playergender: "Male",
      playertype: "Bowler",
      playerbirthdate: "1987-08-10",
      playeraddress: "Rio de Janeiro, Brazil",
      totalmatches: "110",
      totalscore: "1500",
      totalfifties: "3",
      totalcenturies: "0",
      highestscore: "72",
      totalwickets: "200",
      highestwickets: "8",
      playeraverage: "27.3",
      playerstrikerate: "78.9",
      playerdetail: "A right-arm medium pacer with great control over line and length."
    }
];  